title: Inapptics
description: Jekyll template for API documentation.
url: https://docs.inapptics.com
google_analytics_key:
permalink: pretty

collections:
  overview:
    title: Overview
    position: 1
  sdkintegration:
    title: SDK Integration
    position: 2
  apireference:
    title: API Reference
    position: 3
  3rdparty:
    title: 3rd Party Integrations
    position: 4
  samples:
    title: Samples
    position: 9

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default